name: my_slate_template
description: A new Slate package to quickly scaffold your project.
version: 0.0.1
homepage: https://nylo.dev

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  nylo_support: 5.28.0
  flutter:
    sdk: flutter
  args: ^2.4.2
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

screenshots:
  - description: The package logo.
    path: screenshots/logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
